changelog:
  exclude:
    authors:
      - dependabot
      - dependabot[bot]
      - pre-commit-ci
      - pre-commit-ci[bot]
  categories:
    - title: Bugs fixes 🐛
      labels:
        - bug
    - title: Features and enhancements 🎉
      labels:
        - enhancement
        - UI
    - title: Tooling 🔧
      labels:
        - ci-cd
        - tooling
    - title: Documentation 📖
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
